<?php
declare(strict_types=1);

/**
 * KiCom 0.9.27 development-only snapshot ordering guard.
 *
 * Selects exclusively from already read and verified metadata. The caller
 * supplies a trusted verifier that binds each manifest to actual snapshot
 * bytes and full SQLite integrity. This class never opens paths, restores
 * databases, grants authority or guesses order from a random ID suffix.
 */
final class KiComPamSnapshotOrder
{
    /**
     * @param array<int,array<string,mixed>> $manifests
     * @param callable(array):bool $verify  independent KiCom snapshot verifier
     * @return array{ok:bool,code:string,snapshot?:array}
     */
    public static function select(array $manifests, callable $verify): array
    {
        if ($manifests === [] || count($manifests) > 1000) {
            return ['ok' => false, 'code' => 'SNAPSHOT_COUNT_INVALID'];
        }
        $seen = [];
        $rows = [];
        foreach ($manifests as $row) {
            if (!is_array($row)) {
                return ['ok' => false, 'code' => 'SNAPSHOT_METADATA_INVALID'];
            }
            $id = $row['id'] ?? null;
            $created = $row['created_at'] ?? null;
            $sha = $row['sha256'] ?? null;
            if (!is_string($id) || !preg_match('/^[0-9]{14}-[a-f0-9]{10}$/D', $id)
                || isset($seen[$id]) || !is_string($created)
                || !preg_match('/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d\+00:00$/D', $created)
                || !is_string($sha) || !preg_match('/^[a-f0-9]{64}$/D', $sha)) {
                return ['ok' => false, 'code' => 'SNAPSHOT_METADATA_INVALID'];
            }
            $seen[$id] = true;
            $seconds = strtotime($created);
            if ($seconds === false || gmdate('YmdHis', $seconds) !== substr($id, 0, 14)
                || gmdate('Y-m-d\TH:i:s+00:00', $seconds) !== $created) {
                return ['ok' => false, 'code' => 'SNAPSHOT_TIMESTAMP_INVALID'];
            }
            // Optional high-resolution metadata is only useful when it is
            // reliably and independently generated by a trusted future writer.
            // Until such a writer exists, reject any attempt to use this field.
            if (array_key_exists('created_at_us', $row)) {
                return ['ok' => false, 'code' => 'UNTRUSTED_HIGH_RESOLUTION_ORDER'];
            }
            try {
                if ($verify($row) !== true) {
                    return ['ok' => false, 'code' => 'SNAPSHOT_VERIFICATION_FAILED'];
                }
            } catch (Throwable $e) {
                return ['ok' => false, 'code' => 'SNAPSHOT_VERIFICATION_FAILED'];
            }
            $rows[] = ['epoch' => $seconds, 'snapshot' => $row];
        }
        usort($rows, static fn(array $a, array $b): int => $b['epoch'] <=> $a['epoch']);
        // Legacy R3 uses one-second timestamps and a *random* suffix. This
        // ordering cannot prove which of two snapshots is newer within a
        // second. Do not guess from lexicographic filename or mtimes.
        if (count($rows) > 1 && $rows[0]['epoch'] === $rows[1]['epoch']) {
            return ['ok' => false, 'code' => 'SNAPSHOT_ORDER_AMBIGUOUS'];
        }
        return ['ok' => true, 'code' => 'SNAPSHOT_ORDER_VERIFIED',
            'snapshot' => $rows[0]['snapshot']];
    }
}
