<?php
declare(strict_types=1);

/* Exact-response replay v3: recursive canonical fingerprint + encrypted response. */
function kicomReplayDirV3(): string { return kicomAuthDir().'/request_replay_v3'; }
function kicomReplayEnsureV3(): bool {$d=kicomReplayDirV3();if(!is_dir($d)&&!@mkdir($d,0700,true)&&!is_dir($d))return false;$deny=$d.'/.htaccess';if(!is_file($deny))@file_put_contents($deny,"Require all denied\n",LOCK_EX);return true;}
function kicomReplayRequestIdV3(string $id): ?string {$id=trim($id);return preg_match('/^[A-Za-z0-9_.:-]{16,80}$/',$id)?$id:null;}
function kicomReplayFileV3(string $sessionId,string $requestId): string {return kicomReplayDirV3().'/'.hash('sha256',$sessionId.'|'.$requestId).'.json';}
function kicomReplaySensitiveKeyV3(string $key): bool {$key=strtolower($key);foreach(['token','session_id','code','recovery_handle','password','secret','totp','authorization','cookie','api_key'] as $n)if(str_contains($key,$n))return true;return false;}
function kicomReplayCanonicalV3(mixed $v): mixed {if(!is_array($v))return $v;$isList=array_is_list($v);$out=[];if($isList){foreach($v as $x)$out[]=kicomReplayCanonicalV3($x);return $out;}foreach($v as $k=>$x){$k=(string)$k;if(kicomReplaySensitiveKeyV3($k))continue;$out[$k]=kicomReplayCanonicalV3($x);}ksort($out,SORT_STRING);return $out;}
function kicomReplayFingerprintV3(string $operation,array $params=[]): string {$canon=kicomReplayCanonicalV3($params);return hash('sha256',json_encode([$operation,$canon],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)?:'');}
function kicomReplayKeyV3(string $presentedToken,string $requestId): string {return hash('sha256','kicom-request-replay-v3|'.$requestId.'|'.$presentedToken,true);}
function kicomReplaySealV3(array $response,string $presentedToken,string $requestId): ?array {if(!function_exists('openssl_encrypt'))return null;$plain=json_encode($response,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);if($plain===false)return null;$iv=random_bytes(12);$tag='';$cipher=openssl_encrypt($plain,'aes-256-gcm',kicomReplayKeyV3($presentedToken,$requestId),OPENSSL_RAW_DATA,$iv,$tag,'kicom-request-replay-v3');return $cipher===false?null:['iv'=>base64_encode($iv),'tag'=>base64_encode($tag),'cipher'=>base64_encode($cipher)];}
function kicomReplayOpenV3(array $sealed,string $presentedToken,string $requestId): ?array {if(!function_exists('openssl_decrypt'))return null;$iv=base64_decode((string)($sealed['iv']??''),true);$tag=base64_decode((string)($sealed['tag']??''),true);$cipher=base64_decode((string)($sealed['cipher']??''),true);if($iv===false||$tag===false||$cipher===false)return null;$plain=openssl_decrypt($cipher,'aes-256-gcm',kicomReplayKeyV3($presentedToken,$requestId),OPENSSL_RAW_DATA,$iv,$tag,'kicom-request-replay-v3');if($plain===false)return null;$r=json_decode($plain,true);return is_array($r)?$r:null;}
function kicomReplayLookupV3(string $sessionId,string $requestId,string $operation,array $params,string $presentedToken): array {$requestId=kicomReplayRequestIdV3($requestId)??'';if($requestId==='')return ['ok'=>false,'code'=>'REPLAY_REQUEST_ID_INVALID'];$row=kicomAuthJsonRead(kicomReplayFileV3($sessionId,$requestId));if(!is_array($row))return ['ok'=>false,'code'=>'REPLAY_MISS'];if((int)($row['expires_at']??0)<time())return ['ok'=>false,'code'=>'REPLAY_EXPIRED'];if(!hash_equals((string)($row['session_hash']??''),hash('sha256',$sessionId)))return ['ok'=>false,'code'=>'REPLAY_SESSION_MISMATCH'];if(!hash_equals((string)($row['fingerprint']??''),kicomReplayFingerprintV3($operation,$params)))return ['ok'=>false,'code'=>'REPLAY_FINGERPRINT_MISMATCH'];if(!hash_equals((string)($row['presented_token_hash']??''),hash('sha256',$presentedToken)))return ['ok'=>false,'code'=>'REPLAY_TOKEN_MISMATCH'];$response=kicomReplayOpenV3(is_array($row['sealed']??null)?$row['sealed']:[],$presentedToken,$requestId);return is_array($response)?['ok'=>true,'code'=>'REPLAY_HIT','response'=>$response,'replayed'=>true]:['ok'=>false,'code'=>'REPLAY_DECRYPT_FAILED'];}
function kicomReplayStoreV3(string $sessionId,string $requestId,string $operation,array $params,string $presentedToken,array $response,int $ttl=3600): array {$requestId=kicomReplayRequestIdV3($requestId)??'';if($requestId==='')return ['ok'=>false,'code'=>'REPLAY_REQUEST_ID_INVALID'];if(!kicomReplayEnsureV3())return ['ok'=>false,'code'=>'REPLAY_STORAGE_UNAVAILABLE'];$sealed=kicomReplaySealV3($response,$presentedToken,$requestId);if($sealed===null)return ['ok'=>false,'code'=>'REPLAY_SEAL_FAILED'];$row=['schema'=>3,'session_hash'=>hash('sha256',$sessionId),'request_id_hash'=>hash('sha256',$requestId),'fingerprint'=>kicomReplayFingerprintV3($operation,$params),'presented_token_hash'=>hash('sha256',$presentedToken),'sealed'=>$sealed,'created_at'=>gmdate('c'),'expires_at'=>time()+max(60,min(3600,$ttl))];$file=kicomReplayFileV3($sessionId,$requestId);if(is_file($file)){$old=kicomAuthJsonRead($file);if(is_array($old)){if(!hash_equals((string)($old['fingerprint']??''),$row['fingerprint'])||!hash_equals((string)($old['presented_token_hash']??''),$row['presented_token_hash']))return ['ok'=>false,'code'=>'REPLAY_REQUEST_ID_CONFLICT'];return ['ok'=>true,'code'=>'REPLAY_ALREADY_STORED'];}}if(!kicomAuthJsonWrite($file,$row))return ['ok'=>false,'code'=>'REPLAY_WRITE_FAILED'];return ['ok'=>true,'code'=>'REPLAY_STORED'];}
