<?php
declare(strict_types=1);
require_once __DIR__.'/request_guard_v3.php';
require_once __DIR__.'/interrupt_resilience_v2.php';

function kicomRequestGuardBeginV4(string $sessionId,string $requestId,string $operation,array $params,string $presentedToken): array {
    $rid=kicomReplayRequestId($requestId)??'';if($rid==='')return ['ok'=>false,'code'=>'REQUEST_ID_INVALID'];$lf=kicomRequestGuardLockFileV3($sessionId,$rid);if($lf===null)return ['ok'=>false,'code'=>'REQUEST_ID_INVALID'];$lock=@fopen($lf,'c+');if(is_resource($lock))@chmod($lf,0600);if($lock===false||!@flock($lock,LOCK_EX)){if(is_resource($lock))@fclose($lock);return ['ok'=>false,'code'=>'REQUEST_GUARD_LOCK_FAILED'];}
    try{$sha=kicomRequestGuardRequestShaV3($operation,$params,$presentedToken);$claim=kicomResilienceReceiptBeginV2($sessionId,$rid,$operation,$sha,1800);if(empty($claim['ok']))return $claim;if(($claim['code']??'')==='REQUEST_REPLAY'){$receipt=is_array($claim['receipt']??null)?$claim['receipt']:[];$status=(string)($receipt['status']??'');if($status==='IN_PROGRESS')return ['ok'=>true,'code'=>'REQUEST_IN_FLIGHT','mode'=>'IN_FLIGHT','retry_same_request'=>true];if($status==='UNCERTAIN')return ['ok'=>true,'code'=>'REQUEST_UNCERTAIN','mode'=>'UNCERTAIN','inspect_required'=>true];if($status==='DONE'){$replay=kicomReplayLookup($sessionId,$rid,$operation,$params,$presentedToken);if(!empty($replay['ok']))return ['ok'=>true,'code'=>'REQUEST_REPLAY','mode'=>'REPLAY','response'=>$replay['response'],'replayed'=>true];return ['ok'=>false,'code'=>'REQUEST_REPLAY_UNAVAILABLE','detail'=>(string)($replay['code']??'UNKNOWN'),'inspect_required'=>true];}return ['ok'=>false,'code'=>'REQUEST_RECEIPT_STATE_INVALID'];}return ['ok'=>true,'code'=>'REQUEST_EXECUTE','mode'=>'EXECUTE','claim'=>(string)($claim['claim']??''),'replayed'=>false];}finally{@flock($lock,LOCK_UN);@fclose($lock);}
}
function kicomRequestGuardCompleteV4(string $sessionId,string $requestId,string $operation,array $params,string $presentedToken,string $claim,array $response): array {
    $lf=kicomRequestGuardLockFileV3($sessionId,$requestId);if($lf===null)return ['ok'=>false,'code'=>'REQUEST_ID_INVALID'];$lock=@fopen($lf,'c+');if(is_resource($lock))@chmod($lf,0600);if($lock===false||!@flock($lock,LOCK_EX)){if(is_resource($lock))@fclose($lock);return ['ok'=>false,'code'=>'REQUEST_GUARD_LOCK_FAILED'];}
    try{$replay=kicomReplayStore($sessionId,$requestId,$operation,$params,$presentedToken,$response,3600);if(empty($replay['ok']))return ['ok'=>false,'code'=>'REQUEST_REPLAY_STORE_FAILED','detail'=>(string)($replay['code']??'UNKNOWN')];$summary=['code'=>(string)($response['code']??(!empty($response['ok'])?'OK':'FAILED')),'ok'=>!empty($response['ok']),'response_sha256'=>hash('sha256',json_encode($response,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)?:'')];$commit=kicomResilienceReceiptCommitV2($sessionId,$requestId,$claim,$summary);if(empty($commit['ok']))return ['ok'=>false,'code'=>'REQUEST_RECEIPT_COMMIT_FAILED','detail'=>(string)($commit['code']??'UNKNOWN')];return ['ok'=>true,'code'=>'REQUEST_COMMITTED'];}finally{@flock($lock,LOCK_UN);@fclose($lock);}
}
