<?php
declare(strict_types=1);
/** DEV-75 adapter: mutation semantics on the canonical engram_revisions schema. */
final class KiComEngramRevisionAdapter {
 private PDO $db;
 public function __construct(PDO $db){$this->db=$db;$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('PRAGMA foreign_keys=ON');$cols=$db->query('PRAGMA table_info(engram_revisions)')->fetchAll(PDO::FETCH_COLUMN,1);$need=['subject','namespace','id','revision','kind','body','source_kind','source_ref','entry_state','previous_hash','revision_hash'];if(array_diff($need,$cols))throw new RuntimeException('incompatible engram_revisions schema');$db->exec('CREATE TABLE IF NOT EXISTS engram_mutation_receipts(subject TEXT NOT NULL,namespace TEXT NOT NULL,idempotency_key TEXT NOT NULL,operation TEXT NOT NULL,request_hash TEXT NOT NULL,result_json TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(subject,namespace,idempotency_key))');$db->exec('CREATE TABLE IF NOT EXISTS engram_mutation_audit(seq INTEGER PRIMARY KEY AUTOINCREMENT,subject TEXT NOT NULL,namespace TEXT NOT NULL,operation TEXT NOT NULL,engram_id TEXT NOT NULL,revision INTEGER NOT NULL,outcome TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)');}
 private static function digest(array $r):string{$f=['subject','namespace','id','revision','kind','body','source_kind','source_ref','entry_state','previous_hash'];return hash('sha256',json_encode(array_map(fn($k)=>$r[$k],$f),JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR));}
 public function mutate(string $subject,string $ns,string $operation,array $input,string $idem):array{
  if(!preg_match('/\A[a-z0-9][a-z0-9._:-]{0,63}\z/D',$subject)||!preg_match('/\A[a-z0-9][a-z0-9._:-]{0,63}\z/D',$ns)||!preg_match('/\A[a-zA-Z0-9._:-]{8,128}\z/D',$idem))throw new InvalidArgumentException('invalid identity/idempotency');
  if(!in_array($operation,['engram_write','engram_update','engram_archive'],true))throw new InvalidArgumentException('invalid operation');
  $hash=hash('sha256',json_encode([$operation,$input],JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR));$begun=false;
  try{$this->db->exec('BEGIN IMMEDIATE');$begun=true;$q=$this->db->prepare('SELECT operation,request_hash,result_json FROM engram_mutation_receipts WHERE subject=? AND namespace=? AND idempotency_key=?');$q->execute([$subject,$ns,$idem]);if($old=$q->fetch(PDO::FETCH_ASSOC)){if($old['operation']!==$operation||!hash_equals($old['request_hash'],$hash))throw new RuntimeException('idempotency conflict');$this->db->exec('COMMIT');$begun=false;return json_decode($old['result_json'],true,8,JSON_THROW_ON_ERROR);}
   if($operation==='engram_write'){if(array_keys($input)!==['body']||!is_string($input['body'])||$input['body']===''||strlen($input['body'])>4096)throw new InvalidArgumentException('invalid write');$id=bin2hex(random_bytes(16));$rev=1;$kind='technical';$body=$input['body'];$prev=str_repeat('0',64);$state='active';}
   else{foreach(['id','expected_revision','expected_hash'] as $k)if(!array_key_exists($k,$input))throw new InvalidArgumentException('missing concurrency field');$id=$input['id'];if(!is_string($id)||!preg_match('/\A[a-f0-9]{32}\z/D',$id)||!is_int($input['expected_revision'])||!is_string($input['expected_hash']))throw new InvalidArgumentException('invalid concurrency');$q=$this->db->prepare('SELECT * FROM engram_revisions WHERE subject=? AND namespace=? AND id=? ORDER BY revision DESC LIMIT 1');$q->execute([$subject,$ns,$id]);$cur=$q->fetch(PDO::FETCH_ASSOC);if(!$cur||$cur['entry_state']!=='active'||(int)$cur['revision']!==$input['expected_revision']||!hash_equals($cur['revision_hash'],$input['expected_hash'])||!hash_equals($cur['revision_hash'],self::digest($cur)))throw new RuntimeException('revision conflict');$rev=(int)$cur['revision']+1;$kind=$cur['kind'];$prev=$cur['revision_hash'];$state=$operation==='engram_archive'?'withdrawn':'active';$body=$operation==='engram_archive'?$cur['body']:($input['body']??null);if(!is_string($body)||$body===''||strlen($body)>4096)throw new InvalidArgumentException('invalid update');}
   $row=['subject'=>$subject,'namespace'=>$ns,'id'=>$id,'revision'=>$rev,'kind'=>$kind,'body'=>$body,'source_kind'=>'synthetic_test','source_ref'=>'dev75://mutation','entry_state'=>$state,'previous_hash'=>$prev];$row['revision_hash']=self::digest($row);$q=$this->db->prepare('INSERT INTO engram_revisions(subject,namespace,id,revision,kind,body,source_kind,source_ref,entry_state,previous_hash,revision_hash) VALUES(:subject,:namespace,:id,:revision,:kind,:body,:source_kind,:source_ref,:entry_state,:previous_hash,:revision_hash)');$q->execute($row);$result=['id'=>$id,'revision'=>$rev,'revision_hash'=>$row['revision_hash'],'state'=>$state];$json=json_encode($result,JSON_THROW_ON_ERROR);$q=$this->db->prepare('INSERT INTO engram_mutation_receipts(subject,namespace,idempotency_key,operation,request_hash,result_json) VALUES(?,?,?,?,?,?)');$q->execute([$subject,$ns,$idem,$operation,$hash,$json]);$q=$this->db->prepare('INSERT INTO engram_mutation_audit(subject,namespace,operation,engram_id,revision,outcome) VALUES(?,?,?,?,?,"committed")');$q->execute([$subject,$ns,$operation,$id,$rev]);$this->db->exec('COMMIT');$begun=false;return$result;
  }catch(Throwable $e){if($begun)try{$this->db->exec('ROLLBACK');}catch(Throwable $ignored){}throw$e;}}
}
