<?php
declare(strict_types=1);require __DIR__.'/KiComDerivativeGenome.php';
$checks=0;$ok=static function(bool $v,string $m)use(&$checks):void{$checks++;if(!$v){fwrite(STDERR,"FAIL $checks: $m\n");exit(1);}};
$parent=json_decode(file_get_contents(__DIR__.'/../../../source/0.9.26-r3/genome/genome.json'),true,512,JSON_THROW_ON_ERROR);$kp=sodium_crypto_sign_keypair();$pub=sodium_crypto_sign_publickey($kp);$sec=sodium_crypto_sign_secretkey($kp);$otherKp=sodium_crypto_sign_keypair();$otherPub=sodium_crypto_sign_publickey($otherKp);$otherSec=sodium_crypto_sign_secretkey($otherKp);$nonce=bin2hex(random_bytes(32));
$unsigned=KiComDerivativeGenome::build($parent,base64_encode($pub),$nonce);$ok(!KiComDerivativeGenome::verify($unsigned,base64_encode($pub)),'unsigned identity rejected');$child=KiComDerivativeGenome::sign($unsigned,base64_encode($sec));
$ok($child['id']!==$parent['id'],'child id differs');$ok($child['parent']===KiComDerivativeGenome::SOURCE_GENOME_ID,'parent lineage');$ok($child['generation']===26,'generation');$ok(KiComDerivativeGenome::verify($child,base64_encode($pub)),'signed binding verifies');$ok(!KiComDerivativeGenome::verify($child,base64_encode($otherPub)),'other public key rejected');$ok($child['derivative_identity']['native_genome_bound']===true,'native binding flag only after signature');$ok($child['derivative_identity']['authority_granted']===false,'no authority');$ok($child['derivative_identity']['deployment_permitted']===false,'no deployment');$ok($child['derivative_identity']['source_package_sha256']===KiComDerivativeGenome::SOURCE_PACKAGE_SHA256,'package pinned');
$t=$child;$t['derivative_identity']['source_package_sha256']=str_repeat('0',64);$ok(!KiComDerivativeGenome::verify($t,base64_encode($pub)),'package substitution rejected');$t=$child;$t['id']='kicom-child-g26-fake';$ok(!KiComDerivativeGenome::verify($t,base64_encode($pub)),'id substitution rejected');$t=$child;$t['derivative_identity']['authority_granted']=true;$ok(!KiComDerivativeGenome::verify($t,base64_encode($pub)),'authority escalation rejected');$t=$child;$t['derivative_identity']['binding_sha256']=str_repeat('f',64);$ok(!KiComDerivativeGenome::verify($t,base64_encode($pub)),'binding tamper rejected');$t=$child;$t['derivative_identity']['possession_signature_b64']=base64_encode(sodium_crypto_sign_detached(KiComDerivativeGenome::signingMessage($child),$otherSec));$ok(!KiComDerivativeGenome::verify($t,base64_encode($pub)),'foreign signer rejected');
$parent2=$parent;$parent2['id']='kicom-0.9.26-g25r2';try{KiComDerivativeGenome::build($parent2,base64_encode($pub),$nonce);$ok(false,'stale parent rejected');}catch(InvalidArgumentException){$ok(true,'stale parent rejected');}
$child2=KiComDerivativeGenome::build($parent,base64_encode($pub),$nonce);$ok($child2['id']===$unsigned['id'],'same inputs deterministic');$child3=KiComDerivativeGenome::build($parent,base64_encode($pub),bin2hex(random_bytes(32)));$ok($child3['id']!==$unsigned['id'],'fresh nonce changes identity');
fwrite(STDOUT,"OK derivative-genome: {$checks} checks\n");
