<?php
declare(strict_types=1);
require_once __DIR__.'/KiComEngramMcpMutationController.php';
$n=0;function ok(bool $x,string $m):void{global$n;if(!$x)throw new RuntimeException('FAIL '.$m);$n++;echo "PASS $m\n";}function denied(callable $f,string $m):void{$x=false;try{$f();}catch(Throwable $e){$x=true;}ok($x,$m);}function grant(KiComEngramWriteGrant $g,array $o,array $ops,int $now,string $id,string $nonce):string{return $g->issueSynthetic(['v'=>1,'grant_id'=>$id,'owner'=>$o['owner'],'namespace'=>$o['namespace'],'connector_id'=>$o['connector_id'],'token_fingerprint'=>$o['token_fingerprint'],'operations'=>$ops,'nonce'=>$nonce,'iat'=>$now-1,'exp'=>$now+120]);}
$db=new PDO('sqlite::memory:');$g=new KiComEngramWriteGrant(str_repeat('s',48));$svc=new KiComEngramMutationService($db,$g);$ctl=new KiComEngramMcpMutationController($svc);$now=1790128800;$oauth=['authenticated'=>true,'owner'=>'owner-0001','namespace'=>'memory-01','connector_id'=>'connector-01','token_fingerprint'=>'fingerprint-01','scopes'=>['engram.read','engram.write']];$read=$oauth;$read['scopes']=['engram.read'];
$wg=grant($g,$oauth,['engram_write'],$now,'grant-write-01','nonce-write-01');$w=$ctl->handle($oauth,['tool'=>'engram_write','write_grant'=>$wg,'idempotency_key'=>'request-write-01','input'=>['body'=>'synthetic alpha memory']],$now);ok($w['revision']===1&&$w['state']==='active','MCP write reaches SQLite revision 1');
$wg2=grant($g,$oauth,['engram_write'],$now,'grant-write-02','nonce-write-02');denied(fn()=>$ctl->handle($read,['tool'=>'engram_write','write_grant'=>$wg2,'idempotency_key'=>'request-readonly-01','input'=>['body'=>'deny']],$now),'read-only OAuth token denied mutation');
denied(fn()=>$ctl->handle($oauth,['tool'=>'engram_write','owner'=>'attacker-1','write_grant'=>$wg2,'idempotency_key'=>'request-claim-01','input'=>['body'=>'deny']],$now),'MCP owner claim denied');
denied(fn()=>$ctl->handle($oauth,['tool'=>'engram_write','namespace'=>'other-ns','write_grant'=>$wg2,'idempotency_key'=>'request-claim-02','input'=>['body'=>'deny']],$now),'MCP namespace claim denied');
$bad=$oauth;$bad['authenticated']=false;denied(fn()=>$ctl->handle($bad,['tool'=>'engram_write','write_grant'=>$wg2,'idempotency_key'=>'request-unauth-01','input'=>['body'=>'deny']],$now),'unauthenticated OAuth context denied');
$ug=grant($g,$oauth,['engram_update'],$now,'grant-update-01','nonce-update-01');$u=$ctl->handle($oauth,['tool'=>'engram_update','write_grant'=>$ug,'idempotency_key'=>'request-update-01','input'=>['id'=>$w['id'],'body'=>'synthetic beta memory','expected_revision'=>$w['revision'],'expected_hash'=>$w['revision_hash']]],$now);ok($u['revision']===2&&$u['state']==='active','MCP update reaches revision 2');
$ag=grant($g,$oauth,['engram_archive'],$now,'grant-archive-01','nonce-archive-01');$a=$ctl->handle($oauth,['tool'=>'engram_archive','write_grant'=>$ag,'idempotency_key'=>'request-archive-01','input'=>['id'=>$w['id'],'expected_revision'=>$u['revision'],'expected_hash'=>$u['revision_hash']]],$now);ok($a['revision']===3&&$a['state']==='archived','MCP archive appends archived revision');
denied(fn()=>$ctl->handle($oauth,['tool'=>'engram_update','write_grant'=>$ug,'idempotency_key'=>'request-stale-01','input'=>['id'=>$w['id'],'body'=>'deny stale','expected_revision'=>1,'expected_hash'=>$w['revision_hash']]],$now),'stale MCP update denied');
denied(fn()=>$ctl->handle($oauth,['tool'=>'engram_search','write_grant'=>$wg2,'idempotency_key'=>'request-tool-01','input'=>[]],$now),'non-mutation MCP tool rejected');
$cur=$svc->current($oauth['owner'],$oauth['namespace'],$w['id']);ok($cur['revision']==3&&$cur['state']==='archived','SQLite current state remains archived');ok($svc->auditCount()===3,'only three committed mutations audited');ok($db->query('PRAGMA quick_check')->fetchColumn()==='ok','SQLite quick_check ok');echo "KICOM_DEV74_TESTS_PASSED=$n\n";
