#!/usr/bin/env python3
import hashlib,json,shutil,subprocess,sys,tempfile,zipfile,importlib.util
from pathlib import Path
from datetime import datetime,timezone
BASE_SHA='a55f08c10dd460878451cb7190bc82efcd4284cb1864d9c0dc51e63797be3a33';BASE='0.9.10';VER='0.9.11';GID='kicom-0.9.11-g12';PARENT='kicom-0.9.10-g11';GEN=12
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
def run(c): print('+',' '.join(map(str,c)));return subprocess.run(c,text=True,capture_output=True,check=True)
def main():
 b=Path(sys.argv[1]).resolve();o=Path(sys.argv[2]).resolve();s=json.loads((b/'SOURCE-SNAPSHOT.json').read_text());assert s['version']==BASE and s['release_sha256']==BASE_SHA
 for l in (b/'MANIFEST.sha256').read_text().splitlines():
  if l.strip(): h,p=l.split('  ',1);assert sha(b/p)==h,p
 spec=importlib.util.spec_from_file_location('h',Path('tools/build_0910_transaction_buffer.py'));h=importlib.util.module_from_spec(spec);spec.loader.exec_module(h)
 r=Path(tempfile.mkdtemp(prefix='k0911-'))
 try:
  for x in b.iterdir():
   if x.name=='SOURCE-SNAPSHOT.json':continue
   shutil.copytree(x,r/x.name) if x.is_dir() else shutil.copy2(x,r/x.name)
  lp=r/'lib.php';x=lp.read_text();x=h.replace_once(x,"const KICOM_VERSION = '0.9.10';","const KICOM_VERSION = '0.9.11';",'version');lp.write_text(x)
  vp=r/'living.php';x=vp.read_text();x=h.replace_once(x,'/* KiCom Living Architecture 0.9.10 */','/* KiCom Living Architecture 0.9.11 */','comment')
  block=r'''function kicomTransportProfilesFile(): string {return kicomAuthDir().'/transport-profiles.json';}
function kicomTransportProfileId(string $id): ?string {$id=strtolower(trim($id));if($id==='')$id='chat_get';return preg_match('/^[a-z0-9_-]{1,32}$/',$id)?$id:null;}
function kicomTransportProfilesRead(): array {$r=kicomAuthJsonRead(kicomTransportProfilesFile());if(!is_array($r)||!is_array($r['profiles']??null))$r=['schema'=>1,'profiles'=>[]];return $r;}
function kicomTransportProfileView(string $id): array {$id=kicomTransportProfileId($id);if($id===null)return ['ok'=>false,'code'=>'TX_PROFILE_INVALID'];$a=kicomTransportProfilesRead();$p=is_array($a['profiles'][$id]??null)?$a['profiles'][$id]:[];$mx=8192;$safe=max(384,min($mx,(int)($p['safe_fragment_bytes']??768)));$up=max(0,min($mx,(int)($p['failed_upper_bound']??0)));$probe=max($safe+128,(int)floor($safe*1.25));if($up>$safe)$probe=min($probe,max($safe,$up-64));$probe=min($mx,$probe);return ['ok'=>true,'profile'=>$id,'safe_fragment_bytes'=>$safe,'probe_fragment_bytes'=>$probe,'server_max_fragment_bytes'=>$mx,'failed_upper_bound'=>$up,'successes'=>(int)($p['successes']??0),'failures'=>(int)($p['failures']??0)];}
function kicomTransportProfileSuccess(string $id,int $bytes): array {$v=kicomTransportProfileView($id);if(empty($v['ok']))return $v;$id=(string)$v['profile'];$a=kicomTransportProfilesRead();$p=is_array($a['profiles'][$id]??null)?$a['profiles'][$id]:[];$bytes=max(0,min((int)$v['server_max_fragment_bytes'],$bytes));$safe=max((int)$v['safe_fragment_bytes'],$bytes);$up=(int)$v['failed_upper_bound'];if($up>0&&$bytes>=$up)$up=0;$p['safe_fragment_bytes']=$safe;$p['failed_upper_bound']=$up;$p['successes']=(int)($p['successes']??0)+1;$p['last_success_at']=gmdate('c');$p['last_success_bytes']=$bytes;$a['profiles'][$id]=$p;$a['updated_at']=gmdate('c');if(!kicomAuthJsonWrite(kicomTransportProfilesFile(),$a))return ['ok'=>false,'code'=>'TX_PROFILE_WRITE_FAILED'];return kicomTransportProfileView($id);}
function kicomTransportProfileBackoff(string $id,int $failed,int $good=0): array {$v=kicomTransportProfileView($id);if(empty($v['ok']))return $v;$id=(string)$v['profile'];$mx=(int)$v['server_max_fragment_bytes'];if($failed<385)return ['ok'=>false,'code'=>'TX_BACKOFF_INVALID'];$failed=min($mx,$failed);$good=max(0,min($mx,$good));$a=kicomTransportProfilesRead();$p=is_array($a['profiles'][$id]??null)?$a['profiles'][$id]:[];$safe=(int)$v['safe_fragment_bytes'];$cand=$good>0?$good:(int)floor($failed*.70);$cand=max(384,min($safe,$cand));$up=(int)$v['failed_upper_bound'];$up=$up>0?min($up,$failed):$failed;$p['safe_fragment_bytes']=$cand;$p['failed_upper_bound']=$up;$p['failures']=(int)($p['failures']??0)+1;$p['last_failure_at']=gmdate('c');$p['last_failure_bytes']=$failed;$a['profiles'][$id]=$p;$a['updated_at']=gmdate('c');if(!kicomAuthJsonWrite(kicomTransportProfilesFile(),$a))return ['ok'=>false,'code'=>'TX_PROFILE_WRITE_FAILED'];return kicomTransportProfileView($id);}'''
  x=h.insert_after_function(x,'kicomAuthTxCleanup',block)
  x=h.replace_function(x,'kicomAutonomyTxBegin',r'''function kicomAutonomyTxBegin(string $sid,string $stok,string $profile='chat_get'): array {$s=kicomAutonomySessionPeek($sid,$stok);if(empty($s['ok']))return $s;kicomAuthTxCleanup();$pv=kicomTransportProfileView($profile);if(empty($pv['ok']))return $pv;$n=0;foreach(glob(kicomAuthDir().'/tx-*.json')?:[] as $f){$z=kicomAuthJsonRead($f);if(is_array($z)&&hash_equals((string)($z['session_id']??''),$sid))$n++;}if($n>=4)return ['ok'=>false,'code'=>'TX_LIMIT'];$id=substr(kicomAuthRandomHex(10),0,20);$tok=kicomAuthRandomHex(32);$now=time();$exp=min((int)$s['expires_at'],(int)$s['idle_expires_at'],$now+600);$row=['schema'=>2,'id'=>$id,'session_id'=>$sid,'token_hash'=>hash('sha256',$tok),'created_at'=>gmdate('c'),'expires_at'=>$exp,'next_seq'=>0,'bytes'=>0,'payload'=>'','max_bytes'=>65536,'profile'=>(string)$pv['profile'],'max_fragment_bytes'=>(int)$pv['server_max_fragment_bytes'],'safe_fragment_bytes'=>(int)$pv['safe_fragment_bytes'],'probe_fragment_bytes'=>(int)$pv['probe_fragment_bytes'],'last_seq'=>-1,'last_chunk_sha256'=>''];if(!kicomAuthJsonWrite(kicomAuthTxFile($id),$row))return ['ok'=>false,'code'=>'TX_WRITE_FAILED'];return ['ok'=>true,'tx_id'=>$id,'tx_token'=>$tok,'expires_in'=>max(0,$exp-$now),'max_bytes'=>65536,'profile'=>(string)$pv['profile'],'safe_fragment_bytes'=>(int)$pv['safe_fragment_bytes'],'probe_fragment_bytes'=>(int)$pv['probe_fragment_bytes'],'server_max_fragment_bytes'=>(int)$pv['server_max_fragment_bytes']];}''')
  x=h.replace_function(x,'kicomAutonomyTxAppend',r'''function kicomAutonomyTxAppend(string $id,string $tok,int $seq,string $data): array {$z=kicomAutonomyTxGet($id,$tok);if(empty($z['ok']))return $z;$r=$z['row'];$c=kicomDecodeBase64Url($data,true);if($c===null)return ['ok'=>false,'code'=>'TX_CHUNK_ENCODING'];$hs=hash('sha256',$c);$next=(int)($r['next_seq']??0);if($seq!==$next){if($seq===$next-1&&(int)($r['last_seq']??-2)===$seq&&hash_equals((string)($r['last_chunk_sha256']??''),$hs)){$pv=kicomTransportProfileView((string)($r['profile']??'chat_get'));return ['ok'=>true,'code'=>'OK','tx_id'=>$id,'next_seq'=>$next,'bytes'=>(int)($r['bytes']??0),'sha256'=>hash('sha256',(string)($r['payload']??'')),'replayed'=>true]+$pv;}return ['ok'=>false,'code'=>'TX_SEQ','next_seq'=>$next];}$mx=(int)($r['max_fragment_bytes']??8192);if(strlen($c)>$mx)return ['ok'=>false,'code'=>'TX_FRAGMENT_TOO_LARGE','max_fragment_bytes'=>$mx];$p=(string)($r['payload']??'').$c;if(strlen($p)>(int)($r['max_bytes']??65536))return ['ok'=>false,'code'=>'TX_TOO_LARGE'];$r['payload']=$p;$r['bytes']=strlen($p);$r['next_seq']=$seq+1;$r['last_seq']=$seq;$r['last_chunk_sha256']=$hs;$r['updated_at']=gmdate('c');if(!kicomAuthJsonWrite($z['file'],$r))return ['ok'=>false,'code'=>'TX_WRITE_FAILED'];$pv=kicomTransportProfileSuccess((string)($r['profile']??'chat_get'),strlen($c));if(empty($pv['ok']))return $pv;$r['safe_fragment_bytes']=(int)$pv['safe_fragment_bytes'];$r['probe_fragment_bytes']=(int)$pv['probe_fragment_bytes'];kicomAuthJsonWrite($z['file'],$r);return ['ok'=>true,'code'=>'OK','tx_id'=>$id,'next_seq'=>$seq+1,'bytes'=>strlen($p),'sha256'=>hash('sha256',$p),'replayed'=>false]+$pv;}''')
  x=h.insert_after_function(x,'kicomAutonomyTxAppend',r'''function kicomAutonomyTxBackoff(string $id,string $tok,int $failed,int $good=0): array {$z=kicomAutonomyTxGet($id,$tok);if(empty($z['ok']))return $z;$r=$z['row'];$pv=kicomTransportProfileBackoff((string)($r['profile']??'chat_get'),$failed,$good);if(empty($pv['ok']))return $pv;$r['safe_fragment_bytes']=(int)$pv['safe_fragment_bytes'];$r['probe_fragment_bytes']=(int)$pv['probe_fragment_bytes'];$r['updated_at']=gmdate('c');if(!kicomAuthJsonWrite($z['file'],$r))return ['ok'=>false,'code'=>'TX_WRITE_FAILED'];return ['ok'=>true,'code'=>'OK','tx_id'=>$id]+$pv;}''');vp.write_text(x)
  ip=r/'index.php';x=ip.read_text();x=h.replace_once(x,'FACT transport="https:get-read+transaction-buffer+compact-get-batch+post-mutation+guarded-get-bridge"','FACT transport="https:get-read+adaptive-transaction-buffer+compact-get-batch+post-mutation+guarded-get-bridge"','hello');x=h.replace_once(x,'CAPABILITY TRANSACTION_BUFFER begin_nonrotating append_inert_1k commit_single_rotation max64k ttl600','CAPABILITY TRANSACTION_BUFFER adaptive_profile begin_nonrotating append_inert_dynamic idempotent_retry backoff_feedback commit_single_rotation max64k ttl600 server_max8k','cap');x=h.replace_once(x,'RULE transaction-buffer-fragments-are-inert-and-commit-reuses-existing-allowlists-base-sha','RULE transaction-buffer-fragments-are-inert-and-commit-reuses-existing-allowlists-base-sha\',\'RULE adaptive-fragment-profile-learns-success-and-backoff-without-changing-permissions\',\'RULE fragment-retry-is-idempotent-by-sequence-and-sha256','rules');x=h.replace_once(x,"$r=kicomAutonomyTxBegin((string)($_GET['session_id']??''),(string)($_GET['token']??''));","$r=kicomAutonomyTxBegin((string)($_GET['session_id']??''),(string)($_GET['token']??''),(string)($_GET['profile']??'chat_get'));",'begin call');x=h.replace_once(x,"$lines[]='FACT max_fragment_bytes='.(int)$r['max_fragment_bytes'];$lines[]='RULE begin-does-not-rotate-main-session-token';","$lines[]='FACT profile='.kclString((string)$r['profile']);$lines[]='FACT safe_fragment_bytes='.(int)$r['safe_fragment_bytes'];$lines[]='FACT probe_fragment_bytes='.(int)$r['probe_fragment_bytes'];$lines[]='FACT server_max_fragment_bytes='.(int)$r['server_max_fragment_bytes'];$lines[]='RULE begin-does-not-rotate-main-session-token';$lines[]='RULE client-may-probe-upward-and-backoff-after-transport-failure';",'begin out');x=h.replace_once(x,"foreach(['tx_id','next_seq','bytes','sha256'] as $k)if(isset($r[$k]))$lines[]='FACT '.$k.'='.kclString((string)$r[$k]);$lines[]='RULE inert-buffer-only-no-project-mutation';","foreach(['tx_id','next_seq','bytes','sha256','profile','safe_fragment_bytes','probe_fragment_bytes','server_max_fragment_bytes','replayed'] as $k)if(isset($r[$k]))$lines[]='FACT '.$k.'='.kclString((string)$r[$k]);$lines[]='RULE inert-buffer-only-no-project-mutation';$lines[]='RULE duplicate-last-sequence-with-identical-sha-is-idempotent';",'append out');mark="case 'AUTONOMY_TX_STATUS':";back=r'''case 'AUTONOMY_TX_BACKOFF':
    $r=kicomAutonomyTxBackoff((string)($_GET['tx_id']??''),(string)($_GET['tx_token']??''),(int)($_GET['failed_bytes']??0),(int)($_GET['last_good_bytes']??0));$lines=[KCL_PROTOCOL,($r['ok']?'OK':'ERROR').' autonomy_tx_backoff','FACT request_id='.kclString($rid),'FACT code='.kclString((string)($r['code']??'OK'))];foreach(['tx_id','profile','safe_fragment_bytes','probe_fragment_bytes','server_max_fragment_bytes','failed_upper_bound'] as $k)if(isset($r[$k]))$lines[]='FACT '.$k.'='.kclString((string)$r[$k]);$lines[]='RULE performance-feedback-only-no-project-mutation';$lines[]='RULE backoff-does-not-rotate-main-session-token';$lines[]='END';out($lines,$r['ok']?200:422);
''';assert x.count(mark)==1;x=x.replace(mark,back+mark,1);ip.write_text(x)
  ps=r/'memory/project_state.kcl';x=ps.read_text().replace('VERSION "0.9.10"','VERSION "0.9.11"',1).replace('FACT transaction_buffer="inert fragments up to 1KiB, aggregate up to 64KiB, 10m TTL, one session rotation at commit"','FACT transaction_buffer="adaptive per-profile fragments with learned safe/probe sizing, backoff feedback and idempotent retry; aggregate up to 64KiB, 10m TTL, one rotation at commit"',1);ps.write_text(x)
  for f,old,new in [('architecture.kcl','COMPONENT transaction_buffer role="inert server-side fragment buffer; begin/append do not rotate main session, commit validates and rotates once"','COMPONENT transaction_buffer role="adaptive inert fragment buffer with per-profile safe/probe sizing, idempotent retries and backoff feedback; commit validates and rotates once"'),('protocol.kcl','AUTONOMY transaction_buffer="AUTONOMY_TX_BEGIN -> one or more inert AUTONOMY_TX_APPEND fragments -> AUTONOMY_TX_COMMIT with payload SHA; main session rotates once at commit"','AUTONOMY transaction_buffer="AUTONOMY_TX_BEGIN(profile) returns safe/probe sizes -> inert AUTONOMY_TX_APPEND with idempotent retry -> optional AUTONOMY_TX_BACKOFF after transport failure -> AUTONOMY_TX_COMMIT; main session rotates once"')]:p=r/'memory'/f;x=p.read_text();x=h.replace_once(x,old,new,f);p.write_text(x)
  for f,entry,end in [('decisions.kcl','DECISION D017 status=accepted title="Learn transaction fragment size dynamically per transport profile"\nRATIONALE D017 "Successful fragments raise the remembered safe size, transport failures can back off, and idempotent retry removes ambiguity without changing authorization boundaries"\n','END_DECISIONS kicom'),('changelog.kcl','RELEASE "0.9.11" date="2026-09-15" change="Adaptive transport: per-profile safe/probe fragment sizing, upward learning, explicit backoff and idempotent last-fragment retry"\n','END_CHANGELOG kicom')]:p=r/'memory'/f;x=p.read_text();x=h.replace_once(x,end,entry+end,f);p.write_text(x)
  p=r/'memory/next.kcl';x=p.read_text();x=h.replace_once(x,'PRIORITY 5 goal="Continue experience-driven evolution: experience -> insight -> hypothesis -> candidate -> fitness -> promotion -> new experience"','PRIORITY 5 goal="After adaptive fragment sizing is live, evaluate alternative transport paths and compression strategies with the human"\nPRIORITY 6 goal="Continue experience-driven evolution: experience -> insight -> hypothesis -> candidate -> fitness -> promotion -> new experience"','next');p.write_text(x)
  gp=r/'genome/genome.json';g=json.loads(gp.read_text());assert g['id']==PARENT and g['version']==BASE and int(g['generation'])==11;g.update(id=GID,version=VER,parent=PARENT,generation=GEN,created_at=datetime.now(timezone.utc).isoformat(),mutation_reason='Adaptive transport sizing with per-profile learning, backoff and idempotent retry; authorization boundaries unchanged.');
  for c in g['components']:c['sha256']=sha(r/c['path'])
  gp.write_text(json.dumps(g,indent=2,ensure_ascii=False)+'\n');paths=sorted(set([c['path'] for c in g['components']]+['genome/genome.json','memory/project_state.kcl','memory/architecture.kcl','memory/protocol.kcl','memory/decisions.kcl','memory/changelog.kcl','memory/next.kcl']));(r/'MANIFEST.sha256').write_text(''.join(f'{sha(r/p)}  {p}\n' for p in paths));o.unlink(missing_ok=True)
  with zipfile.ZipFile(o,'w',zipfile.ZIP_DEFLATED,compresslevel=9) as z:
   for p in sorted(paths+['MANIFEST.sha256']):z.write(r/p,p)
  print('PACKAGE_SHA256='+sha(o));code=f'''require {str(b/'lib.php')!r};$x=kicomSelfUpdateZipInspect({str(o)!r});if(empty($x["ok"])){{echo "INSPECT=".($x["code"]??"?")."\\n";exit(31);}}$q=kicomSelfUpdateRiskClass($x);echo "RISK=".($q["class"]??"?")."\\nVERSION=".($x["version"]??"?")."\\n";if(($x["version"]??"")!=="0.9.11"||($x["genome"]["id"]??"")!=="kicom-0.9.11-g12")exit(32);''';q=run(['php','-r',code]);print(q.stdout,end='')
  for pp in sorted(r.rglob('*.php')):q=run(['php','-l',str(pp)]);print(q.stdout,end='')
  fr=Path(tempfile.mkdtemp(prefix='k0911fresh-'))
  try:
   with zipfile.ZipFile(o) as z:z.extractall(fr)
   t=Path('/tmp/test0911.php');t.write_text(f'''<?php\nchdir({str(fr)!r});require {str(fr/'lib.php')!r};if(KICOM_VERSION!=="0.9.11")exit(41);if(!kicomEnsureStorage())exit(42);$u=kicomTotpSetupBegin('CI');$ct=intdiv(time(),30);$cd=kicomTotpCodeForCounter($u['secret'],$ct,6);if(empty(kicomTotpSetupConfirm($cd)['ok']))exit(43);$cf=kicomAuthJsonRead(kicomTotpFile());$cf['last_counter']=$ct-1;kicomAuthJsonWrite(kicomTotpFile(),$cf);$s=kicomAutonomySessionOpen($cd);$t=kicomAutonomyTxBegin($s['session_id'],$s['token'],'chat_web');if(empty($t['ok'])||$t['server_max_fragment_bytes']!==8192)exit(44);$c=str_repeat('A',1024);$a=kicomAutonomyTxAppend($t['tx_id'],$t['tx_token'],0,kicomEncodeBase64Url($c));if(empty($a['ok'])||$a['safe_fragment_bytes']<1024)exit(45);$re=kicomAutonomyTxAppend($t['tx_id'],$t['tx_token'],0,kicomEncodeBase64Url($c));if(empty($re['replayed'])||$re['bytes']!==1024)exit(46);$bo=kicomAutonomyTxBackoff($t['tx_id'],$t['tx_token'],1500,1024);if(empty($bo['ok'])||$bo['safe_fragment_bytes']>1024||$bo['failed_upper_bound']!==1500)exit(47);kicomAutonomyTxAbort($t['tx_id'],$t['tx_token']);$t2=kicomAutonomyTxBegin($s['session_id'],$s['token'],'chat_web');if($t2['safe_fragment_bytes']!==1024||$t2['probe_fragment_bytes']<=1024||$t2['probe_fragment_bytes']>=1500)exit(48);$m=kicomReadMemoryResource('PROJECT_STATE');$ops=[['kind'=>'memory_patch','resource'=>'PROJECT_STATE','base_sha256'=>$m['sha256'],'find'=>'STATE active','replace'=>'STATE active']];$pl=json_encode($ops,JSON_UNESCAPED_SLASHES);$ap=kicomAutonomyTxAppend($t2['tx_id'],$t2['tx_token'],0,kicomEncodeBase64Url($pl));$co=kicomAutonomyTxCommit($t2['tx_id'],$t2['tx_token'],$s['token'],hash('sha256',$pl));if(empty($co['ok'])||$co['operations']!==1||empty($co['next_token']))exit(49);echo "ADAPTIVE_TRANSPORT_OK\\n";''');q=run(['php',str(t)]);print(q.stdout,end='')
  finally:shutil.rmtree(fr,ignore_errors=True)
 finally:shutil.rmtree(r,ignore_errors=True)
if __name__=='__main__':main()
